### ISSUE TITLE
Learn from LLMs ：train.rationale.label.jsonl

### ISSUE THREAD

**Issue by walker107** [HKBUNLP/Mr.Harm-EMNLP2023#2]
Hello, thank you for your excellent work !
 When I tried to reproduce “Learn from LLMs” , I got the following error which I can't figure it out.
FileNotFoundError: [Errno 2] No such file or directory: './Data/train.rationale.label.jsonl'

**Comment by ChiYeungLaw** [comment]
All data are provided [here](https://github.com/HKBUNLP/Mr.Harm-EMNLP2023/tree/main/Data). You can simply combine the `train.jsonl` with the rationale data to make the `train.rationale.label.jsonl`.
