### ISSUE TITLE
FHM result 

### ISSUE THREAD

**Issue by walker107** [HKBUNLP/Mr.Harm-EMNLP2023#3]
Hi,author.I have attempted to reproduce the results on the FHM dataset following the dataset settings and hyperparameters specified in the paper. However,  the reproduced results have not been satisfactory, with accuracy and F1 score both hovering around 62%. Could you please advise on any specific considerations to be taken when running experiments on the FHM dataset?

**Comment by DanielLin97** [comment]
Note that the Data Preprocessing of FHM is a bit different from Harm-C/P. Please refer to https://github.com/HKBUNLP/Mr.Harm-EMNLP2023/tree/main/Data#data-preprocess.

**Comment by walker107** [comment]
Thank you so much for your prompt response! I'm eager to understand if the data preprocessing in this paper aligns with MaskPrompt's approach of simply concatenating the original text data with the entity and race information. I tried this way, but unfortunately, I'm only achieving 70% accuracy.
